### ISSUE TITLE
Does not work with 5.4

### ISSUE THREAD

**Issue by ypujante** [jordanvrtanoski/luacpp#4]
Thanks for your project. I tried to compile it with the latest version of lua and it doesn't work due to this [changes](https://www.lua.org/manual/5.4/manual.html#8.3)

```
/mnt/vault/tmp/github/jordanvrtanoski/luacpp/Source/Registry/LuaCompiler.cpp:39:9: error: use of undeclared identifier 'LUA_ERRGCMM'
                        case LUA_ERRGCMM:
                             ^
1 error generated.
```

Since the project was created recently I assumed it was using the latest (or recent) version of lua. I think the main README should at the very minimum states which version of lua you are targeting.
